- name: install apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
- name: copy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart apache
- name: enabled and start apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes