---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Configure index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Open port 80 in UFW
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Check if website is available
  uri:
    url: http://localhost
    return_content: no
  register: website
  until: website.status == 200
  retries: 5
  delay: 5